// Grouped permissions available in the system
export const PERMISSION_GROUPS = [
  {
    title: "Ventas y Facturación",
    permissions: [
      { name: "bills.view", label: "Ver Facturas" },
      { name: "bills.create", label: "Crear Facturas" },
      { name: "bills.update", label: "Modificar Facturas" },
      { name: "billDetails.view", label: "Ver Detalles de Factura" },
      { name: "billDetails.create", label: "Crear Detalles de Factura" },
      { name: "billDetails.update", label: "Modificar Detalles de Factura" },
      { name: "customerQuotes.view", label: "Ver Cotizaciones de Clientes" },
      { name: "customerQuotes.create", label: "Crear Cotizaciones de Clientes" },
      { name: "customerQuotes.update", label: "Modificar Cotizaciones" },
      { name: "salesOrders.view", label: "Ver Pedidos de Venta" },
      { name: "salesOrders.create", label: "Crear Pedidos de Venta" },
      { name: "salesReturns.view", label: "Ver Devoluciones de Venta" },
      { name: "salesReturns.create", label: "Crear Devoluciones" },
      { name: "creditNotes.view", label: "Ver Notas de Crédito" },
      { name: "creditNotes.create", label: "Crear Notas de Crédito" },
    ],
  },
  {
    title: "Compras y Proveedores",
    permissions: [
      { name: "purchaseRequests.view", label: "Ver Solicitudes de Compra" },
      { name: "purchaseRequests.create", label: "Crear Solicitudes de Compra" },
      { name: "requestForQuotations.view", label: "Ver Solicitudes de Cotización" },
      { name: "supplierQuotes.view", label: "Ver Cotizaciones de Proveedores" },
      { name: "supplierQuotes.create", label: "Crear Cotizaciones de Proveedores" },
      { name: "supplierQuotes.update", label: "Modificar Cotizaciones de Prov." },
      { name: "purchaseOrders.view", label: "Ver Órdenes de Compra" },
      { name: "purchaseOrders.create", label: "Crear Órdenes de Compra" },
      { name: "purchaseOrders.update", label: "Modificar Órdenes de Compra" },
      { name: "purchaseOrderForSuppliers.view", label: "Ver Órdenes por Proveedor" },
      { name: "purchaseOrderForSuppliers.update", label: "Modificar Órdenes por Prov." },
      { name: "purchaseReceipts.view", label: "Ver Recepciones de Compra" },
      { name: "purchaseReceipts.create", label: "Crear Recepciones de Compra" },
      { name: "purchaseReturns.view", label: "Ver Devoluciones de Compra" },
      { name: "purchaseReturns.create", label: "Crear Devoluciones de Compra" },
      { name: "suppliers.view", label: "Ver Proveedores" },
      { name: "suppliers.create", label: "Crear Proveedores" },
      { name: "suppliers.update", label: "Modificar Proveedores" },
      { name: "supplierCategories.view", label: "Ver Categorías de Proveedor" },
      { name: "supplierCategories.create", label: "Crear Categoría de Proveedor" },
      { name: "supplierCategories.delete", label: "Eliminar Categoría de Prov." },
    ],
  },
  {
    title: "Inventario y Catálogo",
    permissions: [
      { name: "stock.view", label: "Ver Inventario/Stock" },
      { name: "stock.create", label: "Crear Stock" },
      { name: "stock.update", label: "Modificar Stock" },
      { name: "stock.delete", label: "Eliminar Stock" },
      { name: "products.view", label: "Ver Productos" },
      { name: "products.create", label: "Crear Productos" },
      { name: "products.update", label: "Modificar Productos" },
      { name: "products.delete", label: "Eliminar Productos" },
      { name: "productBrands.view", label: "Ver Marcas" },
      { name: "productBrands.create", label: "Crear Marcas" },
      { name: "productBrands.update", label: "Modificar Marcas" },
      { name: "productBrands.delete", label: "Eliminar Marcas" },
      { name: "productCategories.view", label: "Ver Categorías de Productos" },
      { name: "productCategories.create", label: "Crear Categorías de Productos" },
      { name: "productCategories.update", label: "Modificar Categorías" },
      { name: "productCategories.delete", label: "Eliminar Categorías" },
      { name: "services.view", label: "Ver Servicios" },
      { name: "services.create", label: "Crear Servicios" },
      { name: "services.update", label: "Modificar Servicios" },
      { name: "services.delete", label: "Eliminar Servicios" },
    ],
  },
  {
    title: "Tesorería y Bancos",
    permissions: [
      { name: "banks.view", label: "Ver Bancos" },
      { name: "banks.create", label: "Crear Bancos" },
      { name: "banks.update", label: "Modificar Bancos" },
      { name: "banks.delete", label: "Eliminar Bancos" },
      { name: "accounts.view", label: "Ver Cuentas Bancarias" },
      { name: "accounts.create", label: "Crear Cuentas Bancarias" },
      { name: "accounts.update", label: "Modificar Cuentas Bancarias" },
      { name: "accounts.delete", label: "Eliminar Cuentas Bancarias" },
      { name: "bankMovements.view", label: "Ver Movimientos de Banco" },
      { name: "bankMovements.create", label: "Crear Movimientos de Banco" },
      { name: "checks.view", label: "Ver Cheques" },
      { name: "checks.update", label: "Modificar Cheques" },
      { name: "paymentOrders.view", label: "Ver Órdenes de Pago" },
      { name: "paymentOrders.create", label: "Crear Órdenes de Pago" },
    ],
  },
  {
    title: "Contabilidad",
    permissions: [
      { name: "entries.view", label: "Ver Asientos Contables" },
      { name: "entries.create", label: "Crear Asientos Contables" },
      { name: "entries.update", label: "Modificar Asientos Contables" },
      { name: "entries.delete", label: "Eliminar Asientos Contables" },
      { name: "accountPlans.view", label: "Ver Plan de Cuentas" },
      { name: "accountPlans.create", label: "Crear Cuentas Contables" },
      { name: "accountPlans.update", label: "Modificar Cuentas Contables" },
      { name: "accountPlans.delete", label: "Eliminar Cuentas Contables" },
      { name: "accountantProcesses.view", label: "Ver Procesos Contables" },
      { name: "accountantProcesses.create", label: "Iniciar Proceso Contable" },
      { name: "accountantProcesses.update", label: "Modificar Proceso Contable" },
      { name: "accountingReports.view", label: "Ver Informes Contables" },
    ],
  },
  {
    title: "Recursos Humanos y Nómina",
    permissions: [
      { name: "employees.view", label: "Ver Empleados" },
      { name: "employees.create", label: "Crear Empleados" },
      { name: "employees.update", label: "Modificar Empleados" },
      { name: "employees.delete", label: "Eliminar Empleados" },
      { name: "departments.view", label: "Ver Departamentos" },
      { name: "departments.create", label: "Crear Departamentos" },
      { name: "departments.update", label: "Modificar Departamentos" },
      { name: "departments.delete", label: "Eliminar Departamentos" },
      { name: "positions.view", label: "Ver Cargos" },
      { name: "positions.create", label: "Crear Cargos" },
      { name: "positions.update", label: "Modificar Cargos" },
      { name: "positions.delete", label: "Eliminar Cargos" },
      { name: "schedules.view", label: "Ver Horarios" },
      { name: "schedules.create", label: "Crear Horarios" },
      { name: "schedules.update", label: "Modificar Horarios" },
      { name: "schedules.delete", label: "Eliminar Horarios" },
      { name: "attendance.view", label: "Ver Asistencias" },
      { name: "attendance.create", label: "Registrar Asistencias" },
      { name: "employeeAssignments.create", label: "Crear Asignación" },
      { name: "employeeAssignments.update", label: "Modificar Asignación" },
      { name: "payrollProcesses.view", label: "Ver Liquidación de Nómina" },
      { name: "payrollProcesses.create", label: "Procesar Liquidación de Nómina" },
      { name: "payrollProcesses.update", label: "Modificar Liquidación de Nómina" },
      { name: "payrollProcesses.delete", label: "Eliminar Liquidación de Nómina" },
      { name: "payrollUpdates.view", label: "Ver Novedades de Nómina" },
      { name: "payrollUpdates.create", label: "Registrar Novedad de Nómina" },
      { name: "payrollUpdates.update", label: "Modificar Novedad de Nómina" },
      { name: "payrollVariables.view", label: "Ver Variables de Nómina" },
      { name: "manualConcepts.view", label: "Ver Conceptos Manuales" },
      { name: "manualConcepts.create", label: "Crear Concepto Manual" },
      { name: "manualConcepts.update", label: "Modificar Concepto Manual" },
      { name: "manualConcepts.delete", label: "Eliminar Concepto Manual" },
    ],
  },
  {
    title: "Administración y Seguridad",
    permissions: [
      { name: "users.view", label: "Ver Usuarios" },
      { name: "users.update", label: "Modificar Usuarios" },
      { name: "roles.view", label: "Ver Roles" },
      { name: "roles.create", label: "Crear Roles" },
      { name: "roles.update", label: "Modificar Roles" },
      { name: "roles.delete", label: "Eliminar Roles" },
      { name: "permissions.view", label: "Ver Permisos" },
      { name: "permissions.create", label: "Asociar Permisos" },
      { name: "permissions.update", label: "Modificar Permisos" },
      { name: "permissions.delete", label: "Eliminar Permisos" },
      { name: "branches.view", label: "Ver Sucursales" },
      { name: "branches.create", label: "Crear Sucursales" },
      { name: "branches.update", label: "Modificar Sucursales" },
      { name: "branches.delete", label: "Eliminar Sucursales" },
      { name: "customers.view", label: "Ver Clientes" },
      { name: "customers.create", label: "Crear Clientes" },
      { name: "customers.update", label: "Modificar Clientes" },
      { name: "states.view", label: "Ver Estados de Operación" },
      { name: "states.create", label: "Crear Estado" },
      { name: "states.update", label: "Modificar Estado" },
      { name: "states.delete", label: "Eliminar Estado" },
      { name: "organizations.view", label: "Ver Configuración de la Empresa" },
      { name: "organizations.create", label: "Crear Configuración de la Empresa" },
      { name: "organizations.update", label: "Modificar Configuración de la Empresa" },
      { name: "organizations.delete", label: "Eliminar Configuración de la Empresa" },
    ],
  },
];
